import type { PersistedAppState } from "./persistedState";
import { defaultFixedCosts, defaultOrganization } from "./persistedState";
import { DEFAULT_PAYMENT_METHODS } from "../../domain/settings";
import { toMoney } from "../../domain/money";

export { defaultFixedCosts, defaultOrganization };

/** Demo dataset used on first launch and in browser dev (no localStorage). */
export function createMockAppState(): PersistedAppState {
  return {
    appName: "Academia Horizonte",
    appSubtitle: "Gestion y cobros",
    taxMode: "custom",
    defaultVatRate: 21,
    defaultIncomeTaxReserveRate: 15,
    currencySymbol: "€",
    paymentMethods: [...DEFAULT_PAYMENT_METHODS],
    paymentRecordSeq: { "2026": 4 },
    brandColor: "#0f766e",
    logoPath: null,
    logoDataUrl: null,
    taxIdSeparator: ".",
    fontSize: "normal",
    fontPreset: "font-sans",
    colorScheme: "system",
    autoBackupEnabled: false,
    autoBackupFolderPath: null,
    lastAutoBackupAt: null,
    onboardingCompleted: true,
    organization: {
      legalName: "Academia Horizonte",
      taxId: "B12345678",
      phone: "+34 600 123 456",
      email: "info@academiahorizonte.es",
      streetType: "Calle",
      streetName: "Mayor",
      streetNumber: "12",
      unit: "2B",
      postalCode: "28013",
      city: "Madrid",
      province: "Madrid",
    },
    fixedCosts: {
      selfEmployedFee: toMoney(320),
      rent: toMoney(650),
      other: toMoney(85),
    },
    courses: [
      {
        courseId: "P001",
        courseName: "Ingles B2",
        monthlyFee: toMoney(45),
        billingType: "monthly",
        status: "active",
        createdAt: "2025-09-01",
      },
      {
        courseId: "P002",
        courseName: "Matematicas ESO",
        monthlyFee: toMoney(38),
        billingType: "monthly",
        status: "active",
        createdAt: "2025-09-01",
      },
      {
        courseId: "P003",
        courseName: "Robotica Junior",
        monthlyFee: toMoney(55),
        billingType: "monthly",
        status: "active",
        createdAt: "2026-01-10",
      },
    ],
    students: [
      {
        studentId: "C001",
        guardianTaxId: "12345678A",
        guardianFirstName: "Ana",
        guardianLastName: "Lopez Garcia",
        studentName: "Pedro Lopez",
        age: 12,
        email: "ana.lopez@example.com",
        phone: "+34 611 222 333",
        postalCode: "28013",
        city: "Madrid",
        enrolledAt: "2025-09-15",
        status: "active",
      },
      {
        studentId: "C002",
        guardianTaxId: "12345678A",
        guardianFirstName: "Ana",
        guardianLastName: "Lopez Garcia",
        studentName: "Maria Lopez",
        age: 9,
        email: "ana.lopez@example.com",
        phone: "+34 611 222 333",
        postalCode: "28013",
        city: "Madrid",
        enrolledAt: "2025-09-15",
        status: "active",
      },
      {
        studentId: "C003",
        guardianTaxId: "87654321B",
        guardianFirstName: "Carlos",
        guardianLastName: "Ruiz Mendez",
        studentName: "Lucia Ruiz",
        age: 14,
        email: "carlos.ruiz@example.com",
        phone: "+34 622 333 444",
        postalCode: "28015",
        city: "Madrid",
        enrolledAt: "2025-10-01",
        status: "active",
      },
      {
        studentId: "C004",
        guardianTaxId: "11223344C",
        guardianFirstName: "Elena",
        guardianLastName: "Vega Soto",
        studentName: "Hugo Vega",
        age: 11,
        email: "elena.vega@example.com",
        phone: "+34 633 444 555",
        postalCode: "28020",
        city: "Madrid",
        enrolledAt: "2026-01-20",
        status: "active",
      },
      {
        studentId: "C005",
        guardianTaxId: "55667788D",
        guardianFirstName: "Javier",
        guardianLastName: "Molina Prieto",
        studentName: "Sofia Molina",
        age: 16,
        email: "javier.molina@example.com",
        phone: "+34 644 555 666",
        postalCode: "28028",
        city: "Madrid",
        enrolledAt: "2024-06-01",
        status: "inactive",
        notes: "Baja temporal por mudanza.",
      },
    ],
    classGroups: [
      {
        classGroupId: "G001",
        name: "Ingles B2 - Tarde",
        courseId: "P001",
        weekdays: ["Lunes", "Miércoles"],
        startTime: "16:00",
        endTime: "17:00",
        colorClass: "bg-[var(--color-group-1)]",
        startDate: "2025-09-15",
        capacity: 12,
        status: "active",
      },
      {
        classGroupId: "G002",
        name: "Matematicas ESO - Manana",
        courseId: "P002",
        weekdays: ["Martes", "Jueves"],
        startTime: "10:00",
        endTime: "11:30",
        colorClass: "bg-[var(--color-group-2)]",
        startDate: "2025-09-15",
        capacity: 10,
        status: "active",
      },
      {
        classGroupId: "G003",
        name: "Robotica Junior - Viernes",
        courseId: "P003",
        weekdays: ["Viernes"],
        startTime: "17:30",
        endTime: "19:00",
        colorClass: "bg-[var(--color-group-5)]",
        startDate: "2026-02-01",
        capacity: 8,
        status: "active",
      },
    ],
    enrollments: [
      {
        enrollmentId: "M001",
        studentId: "C001",
        classGroupId: "G001",
        enrolledAt: "2025-09-15",
        status: "active",
      },
      {
        enrollmentId: "M002",
        studentId: "C002",
        classGroupId: "G001",
        enrolledAt: "2025-09-15",
        status: "active",
      },
      {
        enrollmentId: "M003",
        studentId: "C003",
        classGroupId: "G002",
        enrolledAt: "2025-10-01",
        status: "active",
      },
      {
        enrollmentId: "M004",
        studentId: "C004",
        classGroupId: "G003",
        enrolledAt: "2026-02-01",
        status: "active",
      },
      {
        enrollmentId: "M005",
        studentId: "C005",
        classGroupId: "G002",
        enrolledAt: "2024-06-01",
        withdrawnAt: "2025-12-20",
        status: "inactive",
      },
    ],
    paymentRecords: [
      {
        recordId: "F-2026-001",
        issuedOn: "2026-03-01",
        studentId: "C001",
        payerName: "Ana Lopez Garcia",
        lineItems: [
          { description: "Ingles B2 - Pedro Lopez", quantity: 1, unitPrice: toMoney(45) },
          { description: "Ingles B2 - Maria Lopez", quantity: 1, unitPrice: toMoney(45) },
        ],
        total: toMoney(90),
        status: "paid",
        billingPeriod: "Marzo 2026",
        groupIds: ["G001"],
        paymentMethod: "Transferencia",
      },
      {
        recordId: "F-2026-002",
        issuedOn: "2026-03-01",
        studentId: "C003",
        payerName: "Carlos Ruiz Mendez",
        lineItems: [{ description: "Matematicas ESO - Lucia Ruiz", quantity: 1, unitPrice: toMoney(38) }],
        total: toMoney(38),
        status: "pending",
        billingPeriod: "Marzo 2026",
        groupIds: ["G002"],
      },
      {
        recordId: "F-2026-003",
        issuedOn: "2026-02-01",
        studentId: "C003",
        payerName: "Carlos Ruiz Mendez",
        lineItems: [{ description: "Matematicas ESO - Lucia Ruiz", quantity: 1, unitPrice: toMoney(38) }],
        total: toMoney(38),
        status: "paid",
        billingPeriod: "Febrero 2026",
        groupIds: ["G002"],
        paymentMethod: "Bizum",
      },
      {
        recordId: "F-2026-004",
        issuedOn: "2026-03-05",
        studentId: "C004",
        payerName: "Elena Vega Soto",
        lineItems: [{ description: "Robotica Junior - Hugo Vega", quantity: 1, unitPrice: toMoney(55) }],
        total: toMoney(55),
        status: "pending",
        billingPeriod: "Marzo 2026",
        groupIds: ["G003"],
      },
      {
        recordId: "F-2025-012",
        issuedOn: "2025-12-01",
        studentId: "C005",
        payerName: "Javier Molina Prieto",
        lineItems: [{ description: "Matematicas ESO - Sofia Molina", quantity: 1, unitPrice: toMoney(38) }],
        total: toMoney(38),
        status: "voided",
        billingPeriod: "Diciembre 2025",
        groupIds: ["G002"],
      },
    ],
  };
}

/** Empty baseline before SQLite hydration in the desktop app. */
export function createEmptyPersistedState(): PersistedAppState {
  return {
    appName: "Academia PRO",
    appSubtitle: "Gestion y Pagos",
    taxMode: "standard",
    defaultVatRate: 0,
    defaultIncomeTaxReserveRate: 20,
    currencySymbol: "€",
    paymentMethods: [...DEFAULT_PAYMENT_METHODS],
    paymentRecordSeq: {},
    brandColor: "#0f766e",
    logoPath: null,
    logoDataUrl: null,
    taxIdSeparator: ".",
    students: [],
    courses: [],
    paymentRecords: [],
    classGroups: [],
    enrollments: [],
    fixedCosts: defaultFixedCosts,
    organization: defaultOrganization,
    fontSize: "normal",
    fontPreset: "font-sans",
    colorScheme: "system",
    autoBackupEnabled: false,
    autoBackupFolderPath: null,
    lastAutoBackupAt: null,
    onboardingCompleted: false,
  };
}
